from os import PathLike
from types import TracebackType
from typing import Self

_Path = str | PathLike[str]
_Content = bytes | str

ERROR_CODES: dict[str, int]

class CortexError(Exception): ...

class ConsoleRefused(CortexError):
    code: int

class ConsoleBroken(CortexError): ...

class Step:
    @staticmethod
    def run(cmd: str) -> Step: ...
    @staticmethod
    def copy(src: _Path, dst: str) -> Step: ...
    @staticmethod
    def env(key: str, value: str) -> Step: ...
    @staticmethod
    def workdir(dir: str) -> Step: ...

class Image:
    """A base and the steps over it. Every method returns a new ``Image``."""

    def __init__(self, base: str | None = None, steps: list[Step | str] = ...) -> None: ...
    @staticmethod
    def from_dockerfile(content: str) -> Image: ...
    def base(self, base: str) -> Image: ...
    def step(self, step: Step | str) -> Image: ...
    def steps(self, steps: list[Step | str]) -> Image: ...

class Directory:
    """A tree assembled in place. Mounting it with ``HostMount`` takes it."""

    def __init__(self) -> None: ...
    def add_file(self, path: _Path, content: _Content) -> None: ...
    def remove_file(self, path: _Path) -> None: ...
    def mount(self, path: _Path, host_dir: _Path) -> None: ...
    def unmount(self, path: _Path) -> None: ...
    def with_file(self, path: _Path, content: _Content) -> Self: ...
    def with_mount(self, path: _Path, host_dir: _Path) -> Self: ...

class HostMount:
    """A ``Directory`` mounted on this host, for as long as something holds it."""

    def __init__(self, fs: Directory, mountpoint: _Path) -> None: ...
    @property
    def mountpoint(self) -> str: ...

class NetworkAccess:
    def __init__(self, reach: str) -> None: ...
    @staticmethod
    def none() -> NetworkAccess: ...
    @staticmethod
    def host() -> NetworkAccess: ...
    @staticmethod
    def public() -> NetworkAccess: ...
    @staticmethod
    def full() -> NetworkAccess: ...
    def with_host_ports(self, ports: list[int]) -> NetworkAccess: ...
    @property
    def reach(self) -> str: ...
    @property
    def host_ports(self) -> list[int]: ...

class ExecResult:
    code: int
    stdout: bytes
    stderr: bytes
    truncated: bool

class ReadResult:
    data: bytes
    size: int

class ConsoleBuilder:
    """Filled in place and emptied by ``build()``. Every setter returns this builder."""

    def __init__(self) -> None: ...
    def stdio_client(self, cmd: list[str]) -> Self: ...
    def mount(self, mount: HostMount | _Path, at: _Path) -> Self: ...
    def mount_readonly(self, mount: HostMount | _Path, at: _Path) -> Self: ...
    def image(self, image: Image) -> Self: ...
    def snapshot(self, snapshot: bytes) -> Self: ...
    def network(self, network: NetworkAccess) -> Self: ...
    def vcpus(self, vcpus: int) -> Self: ...
    def memory_mib(self, memory_mib: int) -> Self: ...
    def gpu(self, gpu: bool) -> Self: ...
    def gpu_memory_mib(self, gpu_memory_mib: int) -> Self: ...
    def disk_gib(self, disk_gib: int) -> Self: ...
    async def build(self) -> Console: ...

class Console:
    @staticmethod
    def builder() -> ConsoleBuilder: ...
    @property
    def mounts(self) -> list[str]: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def exec(self, cmd: list[str], timeout_ms: int | None = None) -> ExecResult: ...
    async def read(
        self, path: str, offset: int | None = None, len: int | None = None
    ) -> ReadResult: ...
    async def write(self, path: str, data: _Content, offset: int | None = None) -> int: ...
    async def snapshot(self) -> bytes: ...
    async def close(self) -> None: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None: ...
