/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Console {
  static builder(): ConsoleBuilder
  get mounts(): Array<string>
  start(): Promise<void>
  stop(): Promise<void>
  exec(cmd: Array<string>, timeoutMs?: number | undefined | null): Promise<ExecResult>
  read(path: string, offset?: number | undefined | null, len?: number | undefined | null): Promise<ReadResult>
  /** Put `data` in a file, settling with the file's size afterwards. */
  write(path: string, data: Buffer | string, offset?: number | undefined | null): Promise<number>
  snapshot(): Promise<Buffer>
  /** End the session now. Closing twice is the same as closing once. */
  close(): Promise<void>
}
export type JsConsole = Console

/**
 * A [`ConsoleBuilder`], filled in place and emptied by `build()`.
 *
 * In place rather than by value, unlike `Image`: the Rust builder is consumed by each call
 * and is not `Clone`, so there is exactly one of it to hand along. Each method returns the
 * same object so calls chain as they do in Rust.
 */
export declare class ConsoleBuilder {
  constructor()
  stdioClient(cmd: Array<string>): this
  mount(mount: HostMount | string, at: string): this
  mountReadonly(mount: HostMount | string, at: string): this
  image(image: Image): this
  snapshot(snapshot: Buffer): this
  network(network: NetworkAccess): this
  vcpus(vcpus: number): this
  memoryMib(memoryMib: number): this
  gpu(gpu: boolean): this
  gpuMemoryMib(gpuMemoryMib: number): this
  diskGib(diskGib: number): this
  /** Announce the session, and settle with the `Console` the server answered. */
  build(): Promise<Console>
}
export type JsConsoleBuilder = ConsoleBuilder

export declare class Directory {
  constructor()
  addFile(path: string, content: Buffer | string): void
  removeFile(path: string): void
  mount(path: string, hostDir: string): void
  unmount(path: string): void
  /** `addFile`, handing back this same `Directory` so calls chain. */
  withFile(path: string, content: Buffer | string): this
  /** `mount`, handing back this same `Directory` so calls chain. */
  withMount(path: string, hostDir: string): this
}
export type JsDirectory = Directory

/**
 * A tree mounted on this host, for as long as something holds it.
 *
 * Held behind an [`Arc`] so that passing one to a console builder does not take it from
 * the JavaScript object: both hold the mount, and it comes down when the last of them
 * lets go — the builder's copy with the console, the JavaScript one with garbage
 * collection.
 */
export declare class HostMount {
  constructor(fs: Directory, mountpoint: string)
  get mountpoint(): string
}
export type JsHostMount = HostMount

export declare class Image {
  constructor(base?: string | undefined | null, steps?: Array<Step | string>)
  static fromDockerfile(content: string): Image
  base(base: string): Image
  step(step: Step | string): Image
  steps(steps: Array<Step | string>): Image
  toString(): string
}
export type JsImage = Image

export declare class NetworkAccess {
  constructor(reach: string)
  static none(): NetworkAccess
  static host(): NetworkAccess
  static public(): NetworkAccess
  static full(): NetworkAccess
  withHostPorts(ports: Array<number>): NetworkAccess
  get reach(): string
  get hostPorts(): Array<number>
}
export type JsNetworkAccess = NetworkAccess

export declare class Step {
  static run(cmd: string): Step
  static copy(src: string, dst: string): Step
  static env(key: string, value: string): Step
  static workdir(dir: string): Step
  toString(): string
}
export type JsStep = Step

export interface ExecResult {
  code: number
  stdout: Buffer
  stderr: Buffer
  truncated: boolean
}

export interface ReadResult {
  data: Buffer
  /** A JavaScript number, so exact up to 2^53 bytes. */
  size: number
}
